apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: binderhub
  namespace: argocd 
spec:
  generators:
  - git:
      repoURL: https://gitlab.com/ska-telescope/src/src-services-deployment.git 
      revision: HEAD 
      files:
      - path: 'binderhub/binderhub-values.yaml'
  template:
    metadata:
      name: binderhub
    spec:
      project: binder
      source:
        helm:
          values: |-
            {{values}}
        repoURL: https://jupyterhub.github.io/helm-chart 
        targetRevision: 0.2.0-n648.h8d1c0e7 
        chart: jupyterhub/binderhub
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: binder-prod
      syncPolicy:
        automated:
          selfHeal: true
          prune: false 
