apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: binderhub-accessories
spec:
  project: binder 
  source:
    path: binderhub/accessories
    repoURL: 'https://gitlab.com/ska-telescope/src/src-services-deployment.git' 
    targetRevision: HEAD
  destination:
    namespace: binder-prod 
    server: https://kubernetes.default.svc
