apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: binderhub-data-cephfs-rw-pvc
 namespace: binder-prod
spec:
 storageClassName: rook-cephfs
 accessModes:
 - ReadWriteMany
 resources:
   requests:
    storage: 25Gi
