apiVersion: batch/v1
kind: CronJob
metadata:
  name: rucio-postgres-backup
  namespace: rucio
spec:
  # Backup the database every day at 2AM
  schedule: "0 2 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: rucio-postgres-backup
            image: 130.246.213.80:5000/bitnami/postgresql:15.3.0-debian-11-r0
            command: ["/bin/sh"]
            args: ["-c", 'pg_dump --dbname=postgresql://postgres:$PG_PASS@rucio-postgres-postgresql:5432/rucio --exclude-table-data "rucio.*_history" -v > /tmp/backups/backup-$(date +"%m-%d-%Y-%H-%M").sql']
            env:
            - name: PG_PASS
              valueFrom:
                secretKeyRef:
                  name: rucio-postgres-postgresql
                  key: postgres-password 
            volumeMounts:
            - mountPath: /tmp/backups
              name: postgres-backups
          restartPolicy: Never
          volumes:
          - name: postgres-backups
            hostPath:
            # Ensure the file directory is created and has the correct permissions.
              path: /backups
              type: DirectoryOrCreate
          nodeSelector:
            kubernetes.io/hostname: srcnet-workload-1-md-0-68nhg
