binderhub:
  registry:
    username: "srcdev"
    password: "616b6857-b3a3-4e57-8fef-fcee9c980e55"
  config:
    BinderHub:
      hub_url: https://srcdev.skatelescope.org/
  jupyterhub:
    hub:
      config:
        GenericOAuthenticator:
          client_id: "a5abd5ee-d106-4794-8e22-e80974e9a954"
          client_secret: "PXJcd53bfKW2a3opyHxsPvDAL4gt8ZCdGU_TMYTegkTHoJpriBawErIZLkw7pahvze8kGGmmjdD8FzAJZ0P_pA"
          oauth_callback_url: "https://srcdev.skatelescope.org/hub/oauth_callback"
      services:
        binder:
          oauth_redirect_uri: "https://srcdev.skatelescope.org/sdc-bh/oauth_callback"