binderhub:
  registry:
    username: "srcdev"
    password: "dckr_pat_pWzDrMLW7_V0lwgZ9irULixgxRI"
  config:
    BinderHub:
      hub_url: https://jupyterhub.srcdev.skao.int/
      base_url: /
  jupyterhub:
    hub:
      config:
        GenericOAuthenticator:
          client_id: "a5abd5ee-d106-4794-8e22-e80974e9a954"
          client_secret: "PXJcd53bfKW2a3opyHxsPvDAL4gt8ZCdGU_TMYTegkTHoJpriBawErIZLkw7pahvze8kGGmmjdD8FzAJZ0P_pA"
          oauth_callback_url: "https://jupyterhub.srcdev.skao.int/hub/oauth_callback"
      services:
        binder:
          oauth_redirect_uri: "https://binderhub.srcdev.skao.int/oauth_callback"
      db:
        type: sqlite-memory
        #pvc:
        #  storageClassName: csi-cinder-sc-retain
    singleuser:
      profileList:
      - display_name: "Default environment"
        description: "Default Jupyter Notebook environment"
      - display_name: "Pangeo base"
        description: "Includes Dask Gateway"
        kubespawner_override:
          image: pangeo/base-notebook:2023.02.27
      - display_name: "SDC1 Solution"
        description: "An Ubuntu 18.04 based image with Python 3.7"
        kubespawner_override:
          image: registry.gitlab.com/ska-telescope/sdc/sdc1-solution:scipy-nb-ubuntu18
      - display_name: "Image co-adding - SWARP"
        description: "Image co-adding with SWARP: https://gitlab.com/ska-telescope/src/src-workloads/-/tree/master/tasks/image-coadding-SWARP"
        kubespawner_override:
          image: registry.gitlab.com/ska-telescope/src/src-workloads/image-coadding-swarp-jupyter:0.0.1
      - display_name: "Mosaicking - SWARP"
        description: "Mosaicking with SWARP: https://gitlab.com/ska-telescope/src/src-workloads/-/tree/master/tasks/mosaicking-SWARP"
        kubespawner_override:
          image: registry.gitlab.com/ska-telescope/src/src-workloads/mosaicking-swarp-jupyter:0.0.2
      - display_name: "Source finding"
        description: "Source finding with PyBDSF: https://gitlab.com/ska-telescope/src/src-workloads/-/tree/master/tasks/source-finding-PYBDSF"
        kubespawner_override:
          image: registry.gitlab.com/ska-telescope/src/src-workloads/source-finding-pybdsf-jupyter:0.0.3
      - display_name: "ipyaladin Environment"
        description: "Scipy notebook with ipyaladin 0.2.5 installed"
        kubespawner_override:
          image: 130.246.213.80:5000/scipy-notebook-ipyaladin:0.0.1
      - display_name: "Dask-Rucio-IVOA Demo notebook"
        description: "Built on minimal-notebook"
        kubespawner_override:
          image: registry.gitlab.com/ska-telescope/src/src-workloads/distributed-analysis-dask-jupyter:0.0.1
      - display_name: "VSCode IDE"
        description: "Prototype IDE environment developed by LAPP"
        kubespawner_override:
          default_url: /vscode
          image: gitlab-registry.in2p3.fr/must/kubernetes/jupyter-environments/vscode:latest
dask-gateway:
  gateway:
    backend:
      image:
        name: registry.gitlab.com/ska-telescope/src/src-workloads/distributed-analysis-dask-gateway-backend
        tag: 0.0.1
