image:
  repository: registry.gitlab.com/ska-telescope/src/ska-rucio-ivoa-integration
  image: dachs
  tag: latest
  pullPolicy: Always

deployment:
  namespace: rucio-ivoa-integration

svc:
  dachs:
    gavorc_server_url: "https://ivoa.dachs.srcdev.skao.int:443"
    gavorc_server_port: 8080
    dachs_postgres_host: "postgres-metadata-postgresql.rucio.svc.cluster.local"
    dachs_postgres_dbname: "metadata"
    ivoa_authority: "test.skao"
