apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: skaha-pvc
  namespace: skaha-system
spec:
  storageClassName: csi-cinder-sc-delete
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
